services:
  - type: web
    name: fpr-team10-test
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - Dockerfile
        - .env.example
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 8080
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_URL
        value: https://fpr-team10-test.onrender.com
      # These will be filled after DB creation:
      - key: DB_HOST
        value: 
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: 
      - key: DB_USERNAME
        value: 
      - key: DB_PASSWORD
        value: 
